### ISSUE TITLE
Searching for applications briefly shows wrong UI

### ISSUE THREAD

**Issue by poi33** [enonic/app-applications#449]
When searching for an app the ap can show for a brief moment: 
![image](https://user-images.githubusercontent.com/3340349/130039135-5cccafaa-4cc5-4388-b2d5-029fdf0d5fff.png)
And after waiting a second or two:
![image](https://user-images.githubusercontent.com/3340349/130039249-d7be9fbd-d24f-4f5d-91bc-49dd01ce6470.png)
The correct result shows up.

**Comment by alansemenov** [comment]
Important note: this only happens when you type in keywords **while** the initial list is being loaded. If you wait for the list to load after opening the dialog and **then** search for an app, everything works as it should.

So we need to reset the original request and make sure it won't display any output, if a new search is initiated.
